# permissions for end users to view dlcpods.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dlcpod-viewer-role
rules:
- apiGroups:
  - docgroup.com.my.domain
  resources:
  - dlcpods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - docgroup.com.my.domain
  resources:
  - dlcpods/status
  verbs:
  - get
