apiVersion: docgroup.com/v1alpha1
kind: DLCPod
metadata:
  name: deepspeech
  namespace: default
spec:
  secret:
    name: dlcpod-client-credentials
  jobs:
  - name: job
    image: zhuangweikang/deepspeech-dev:latest
    command: ["bash"]
    datasource:
      name: LibriSpeech
      bucket: vuzhuangwei
      keys:
      - LibriSpeech/train
      - LibriSpeech/val
    qos:
      usecache: true
      maxmemorymill: 10000
      lazyloading: true
    tty: true
    stdin: true
