apiVersion: docgroup.com/v1alpha1
kind: DLCPod
metadata:
  name: imagenet
  namespace: default
spec:
  secret:
    name: dlcpod-client-credentials
  jobs:
  - name: job
    image: zhuangweikang/imagedatasets-dev:latest
    command: ["bash"]
    datasource:
      name: Imagenet-Mini
      bucket: vuzhuangwei
      keys:
        train:
          samples:
            - Imagenet-Mini/train/samples
          manifests: 
            - Imagenet-Mini/train/manifest.csv
        validation:
          samples:
            - Imagenet-Mini/val/samples
          manifests: 
            - Imagenet-Mini/val/manifest.csv
    qos:
      usecache: true
      MaxPartMill: 10000
      lazyloading: true
    tty: true
    stdin: true
