apiVersion: docgroup.com/v1alpha1
kind: DLCPod
metadata:
  name: deepspeech
  namespace: default
spec:
  secret:
    name: dlcpod-client-credentials
  jobs:
  - name: job
    image: zhuangweikang/deepspeech-dev:latest
    command: ["bash"]
    datasource:
      name: LibriSpeech
      bucket: vuzhuangwei
      keys:
        train:
          samples:
            - LibriSpeech/train/wav
          targets:
            - LibriSpeech/train/txt
          manifests:
            - LibriSpeech/train/manifest.csv
        validation:
          samples:
            - LibriSpeech/val/wav
          targets:
            - LibriSpeech/val/txt
          manifests:
            - LibriSpeech/val/manifest.csv
        test:
          samples:
            - LibriSpeech/test/wav
          targets:
            - LibriSpeech/test/txt
          manifests:
            - LibriSpeech/test/manifest.csv
    qos:
      usecache: true
      MaxPartMill: 10000
      lazyloading: true
    tty: true
    stdin: true