apiVersion: docgroup.com/v1alpha1
kind: DLCPod
metadata:
  name: imagenet-mini1
  namespace: default
spec:
  secret:
    name: dlcpod-client-secret
  nodeSelector:
    dlcache: Client
  jobs:
  - name: job
    image: zhuangweikang/imagenet:latest
    # command: ["python3", "main.py"]
    command: ["bash"]
    datasource:
      name: Imagenet-Mini
      bucket: zhuangwei-bucket
      keys:
      - imagenet-mini/train
      - imagenet-mini/val
    configurations:
      usecache: true
      maxmemory: 0
      durabilityindisk: 1440
      lazyloading: true
    tty: true
    stdin: true
