---
apiVersion: v1
kind: Secret
metadata:
  name: dlcpod-client-secret
  namespace: default
type: Opaque
stringData:
  client.conf: |
    [AWS]
    AWS_ACCESS_KEY_ID=<your key id>
    AWS_SECRET_ACCESS_KEY=<your key>
    REGION_NAME=<your region name>
---
apiVersion: docgroup.com/v1alpha1
kind: DLCPod
metadata:
  name: imagenet-mini0
  namespace: default
spec:
  secret:
    name: dlcpod-client-secret
  nodeSelector:
    dlcache: Client
  jobs:
  - name: job
    image: centaurusinfra/imagenet:latest
    # command: ["python3", "main.py"]
    command: ["bash"]
    datasource:
      name: Imagenet-Mini-Obj
      bucket: zhuangwei-bucket
      keys:
      - Imagenet-Mini-Obj/train
      - Imagenet-Mini-Obj/val
    configurations:
      usecache: true
      maxmemory: 0
      durabilityindisk: 1440
      lazyloading: true
    tty: true
    stdin: true
