apiVersion: v1
kind: Secret
metadata:
  name: dlcpod-client-credentials
  namespace: default
type: Opaque
data:
  aws_access_key_id: xxx
  aws_secret_access_key: xxx
  region_name: xxx
  dlcache_user: xxx
  dlcache_pwd: XXX