apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dlcache-manager-worker
  labels:
    app: manager-worker
spec:
  selector:
    matchLabels:
      app: manager-worker
  template:
    metadata:
      labels:
        app: manager-worker
    spec:
      containers:
      - name: dlcache-manager-worker
        image: zhuangweikang/dlcache-dev:manager-worker
        imagePullPolicy: Always
        ports:
        - name: listen-port
          containerPort: 50052
        volumeMounts:
        - name: nfs-storage
          mountPath: /nfs_storage
        stdin: true
        tty: true
        env:
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
      volumes:
        - name: nfs-storage
          hostPath:
            path: /nfs_storage