apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dlcache-manager-worker
  labels:
    app: manager-worker
spec:
  selector:
    matchLabels:
      app: manager-worker
  template:
    metadata:
      labels:
        app: manager-worker
    spec:
      containers:
      - name: dlcache-manager-worker
        image: zhuangweikang/dlcache-dev:manager-worker
        imagePullPolicy: Always
        ports:
        - name: listen-port
          containerPort: 50052
        volumeMounts:
        - name: 129-59-234-236
          mountPath: /129.59.234.236
        - name: 129-59-234-237
          mountPath: /129.59.234.237
        - name: 129-59-234-238
          mountPath: /129.59.234.238
        - name: 129-59-234-239
          mountPath: /129.59.234.239
        - name: 129-59-234-240
          mountPath: /129.59.234.240
        - name: 129-59-234-241
          mountPath: /129.59.234.241
        stdin: true
        tty: true
      volumes:
        - name: 129-59-234-236
          nfs: 
            server: 129.59.234.236
            path: /nfs_storage
        - name: 129-59-234-237
          nfs: 
            server: 129.59.234.237
            path: /nfs_storage
        - name: 129-59-234-238
          nfs: 
            server: 129.59.234.238
            path: /nfs_storage
        - name: 129-59-234-239
          nfs: 
            server: 129.59.234.239
            path: /nfs_storage
        - name: 129-59-234-240
          nfs: 
            server: 129.59.234.240
            path: /nfs_storage
        - name: 129-59-234-241
          nfs: 
            server: 129.59.234.241
            path: /nfs_storage