# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import databus.dbus_pb2 as dbus__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class ManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.connect = channel.unary_unary(
                '/dbus.Manager/connect',
                request_serializer=dbus__pb2.ConnectRequest.SerializeToString,
                response_deserializer=dbus__pb2.ConnectResponse.FromString,
                )
        self.register = channel.unary_unary(
                '/dbus.Manager/register',
                request_serializer=dbus__pb2.RegisterRequest.SerializeToString,
                response_deserializer=dbus__pb2.RegisterResponse.FromString,
                )
        self.deregister = channel.unary_unary(
                '/dbus.Manager/deregister',
                request_serializer=dbus__pb2.DeregisterRequest.SerializeToString,
                response_deserializer=dbus__pb2.DeregisterResponse.FromString,
                )
        self.handle_datamiss = channel.unary_unary(
                '/dbus.Manager/handle_datamiss',
                request_serializer=dbus__pb2.DataMissRequest.SerializeToString,
                response_deserializer=dbus__pb2.DataMissResponse.FromString,
                )
        self.join = channel.unary_unary(
                '/dbus.Manager/join',
                request_serializer=dbus__pb2.WorkerJoinRequest.SerializeToString,
                response_deserializer=dbus__pb2.WorkerJoinResponse.FromString,
                )


class ManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def connect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deregister(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def handle_datamiss(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def join(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'connect': grpc.unary_unary_rpc_method_handler(
                    servicer.connect,
                    request_deserializer=dbus__pb2.ConnectRequest.FromString,
                    response_serializer=dbus__pb2.ConnectResponse.SerializeToString,
            ),
            'register': grpc.unary_unary_rpc_method_handler(
                    servicer.register,
                    request_deserializer=dbus__pb2.RegisterRequest.FromString,
                    response_serializer=dbus__pb2.RegisterResponse.SerializeToString,
            ),
            'deregister': grpc.unary_unary_rpc_method_handler(
                    servicer.deregister,
                    request_deserializer=dbus__pb2.DeregisterRequest.FromString,
                    response_serializer=dbus__pb2.DeregisterResponse.SerializeToString,
            ),
            'handle_datamiss': grpc.unary_unary_rpc_method_handler(
                    servicer.handle_datamiss,
                    request_deserializer=dbus__pb2.DataMissRequest.FromString,
                    response_serializer=dbus__pb2.DataMissResponse.SerializeToString,
            ),
            'join': grpc.unary_unary_rpc_method_handler(
                    servicer.join,
                    request_deserializer=dbus__pb2.WorkerJoinRequest.FromString,
                    response_serializer=dbus__pb2.WorkerJoinResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dbus.Manager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Manager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def connect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dbus.Manager/connect',
            dbus__pb2.ConnectRequest.SerializeToString,
            dbus__pb2.ConnectResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dbus.Manager/register',
            dbus__pb2.RegisterRequest.SerializeToString,
            dbus__pb2.RegisterResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def deregister(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dbus.Manager/deregister',
            dbus__pb2.DeregisterRequest.SerializeToString,
            dbus__pb2.DeregisterResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def handle_datamiss(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dbus.Manager/handle_datamiss',
            dbus__pb2.DataMissRequest.SerializeToString,
            dbus__pb2.DataMissResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def join(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dbus.Manager/join',
            dbus__pb2.WorkerJoinRequest.SerializeToString,
            dbus__pb2.WorkerJoinResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class ManagerWorkerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.download = channel.unary_unary(
                '/dbus.ManagerWorker/download',
                request_serializer=dbus__pb2.DownloadFileRequest.SerializeToString,
                response_deserializer=dbus__pb2.DownloadFileResponse.FromString,
                )
        self.extract = channel.unary_unary(
                '/dbus.ManagerWorker/extract',
                request_serializer=dbus__pb2.ExtractFileRequest.SerializeToString,
                response_deserializer=dbus__pb2.ExtractFileResponse.FromString,
                )


class ManagerWorkerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def download(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def extract(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ManagerWorkerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'download': grpc.unary_unary_rpc_method_handler(
                    servicer.download,
                    request_deserializer=dbus__pb2.DownloadFileRequest.FromString,
                    response_serializer=dbus__pb2.DownloadFileResponse.SerializeToString,
            ),
            'extract': grpc.unary_unary_rpc_method_handler(
                    servicer.extract,
                    request_deserializer=dbus__pb2.ExtractFileRequest.FromString,
                    response_serializer=dbus__pb2.ExtractFileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dbus.ManagerWorker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ManagerWorker(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def download(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dbus.ManagerWorker/download',
            dbus__pb2.DownloadFileRequest.SerializeToString,
            dbus__pb2.DownloadFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def extract(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dbus.ManagerWorker/extract',
            dbus__pb2.ExtractFileRequest.SerializeToString,
            dbus__pb2.ExtractFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class LoggerStub(object):
    """CC periodically sends log messages tO GM
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.call = channel.stream_unary(
                '/dbus.Logger/call',
                request_serializer=dbus__pb2.LogItem.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class LoggerServicer(object):
    """CC periodically sends log messages tO GM
    """

    def call(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LoggerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'call': grpc.stream_unary_rpc_method_handler(
                    servicer.call,
                    request_deserializer=dbus__pb2.LogItem.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dbus.Logger', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Logger(object):
    """CC periodically sends log messages tO GM
    """

    @staticmethod
    def call(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/dbus.Logger/call',
            dbus__pb2.LogItem.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
