apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-redis-proxy-conf
  namespace: default
data:
  envoy.yaml: |
    admin:
      access_log_path: "/dev/null"
      address:
        socket_address:
          protocol: TCP
          address: 0.0.0.0
          port_value: 8001
    static_resources:
      listeners:
      - name: redis_listener
        address:
          socket_address:
            address: 0.0.0.0
            port_value: 6379
        filter_chains:
        - filters:
          - name: envoy.filters.network.redis_proxy
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.redis_proxy.v3.RedisProxy
              stat_prefix: egress_redis
              settings:
                op_timeout: 5s
                enable_redirection: true
                max_buffer_size_before_flush: 1024
                buffer_flush_timeout: 0.003s
              prefix_routes:
                catch_all_route:
                  cluster: redis_cluster
              downstream_auth_username:
                inline_string: "${REDIS_PROXY_USERNAME}"
              downstream_auth_password:
                inline_string: "${REDIS_PROXY_PWD}"
      clusters:
      - name: redis_cluster
        cluster_type:
          name: envoy.clusters.redis
        connect_timeout: 10s
        cleanup_interval: 3s
        lb_policy: CLUSTER_PROVIDED
        typed_extension_protocol_options:
          envoy.filters.network.redis_proxy:
            "@type": type.googleapis.com/google.protobuf.Struct
            value:
              auth_password:
                inline_string: "${REDIS_PWD}"
        load_assignment:
          cluster_name: redis_cluster
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: redis-cluster
                    port_value: 6379