apiVersion: v1
kind: ConfigMap
metadata:
  name: dlcpod-manager-config
  namespace: default
data:
  manager.conf: |
    [manager]
    bind=[::]
    port=50051
    attenuationFactor=2
    stepFactor=0.5
    costFactor=0.5

    [mongodb]
    username=docgroup
    password=docgroup
    host=mongo
    port=27017
    db=Cacher
