---
apiVersion: v1
kind: Service
metadata:
  name: dlcpod-manager
spec:
  type: NodePort
  ports:
  - port: 50051
    targetPort: 50051
    nodePort: 32200
  selector:
    app: manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dlcpod-manager
  labels:
    app: manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manager
  template:
    metadata:
      labels:
        app: manager
      # annotations:
      #   k8s.v1.cni.cncf.io/networks: macvlan-conf
    spec:
      # nodeSelector:
      #   dlcache: CacheCluster
      containers:
      - name: dlcpod-manager
        image: zhuangweikang/dlcpod-dev:manager
        imagePullPolicy: Always
        command: ["bash"]
        ports:
        - name: listen-port
          containerPort: 50051
        volumeMounts:
        - name: configuration
          mountPath: /configs/manager
        # - name: nfs-volume
        #   mountPath: /nfs-master
        - name: 129-59-234-240
          mountPath: /129.59.234.240
        - name: 129-59-234-236
          mountPath: /129.59.234.236
        - name: 129-59-234-238
          mountPath: /129.59.234.238
        stdin: true
        tty: true
      volumes:
        - name: configuration
          configMap:
            name: dlcpod-manager-config
        # - name: nfs-volume
        #   persistentVolumeClaim:
        #     claimName: nfs-pvc
        - name: 129-59-234-240
          nfs: 
            server: 129.59.234.240
            path: /nfs_storage
        - name: 129-59-234-236
          nfs: 
            server: 129.59.234.236
            path: /nfs_storage
        - name: 129-59-234-238
          nfs: 
            server: 129.59.234.238
            path: /nfs_storage